services:
  postgres:
    image: postgres:13
    container_name: enutritrack_postgres
    environment:
      POSTGRES_DB: enutritrack
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 4ndr3$G22004
    ports:
      - '5433:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./scripts/init-db.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - enutritrack-network
    healthcheck:
      test: [ 'CMD-SHELL', 'pg_isready -U postgres -d enutritrack' ]
      interval: 10s
      timeout: 5s
      retries: 5

  couchbase:
    image: couchbase/server:community-7.1.1
    container_name: enutritrack_couchbase
    ports:
      - '8091-8097:8091-8097'
      - '11210:11210'
      - '11207:11207'
    environment:
      - COUCHBASE_ADMINISTRATOR_USERNAME=Alfredo
      - COUCHBASE_ADMINISTRATOR_PASSWORD=alfredo124
    volumes:
      - couchbase_data:/opt/couchbase/var
    networks:
      - enutritrack-network

  redis:
    image: redis:7-alpine
    container_name: enutritrack_redis
    ports:
      - '6379:6379'
    command: redis-server --requirepass redispassword
    volumes:
      - redis_data:/data
    networks:
      - enutritrack-network
    healthcheck:
      test: [ 'CMD', 'redis-cli', '-a', 'redispassword', 'ping' ]
      interval: 10s
      timeout: 3s
      retries: 5

volumes:
  postgres_data:
  couchbase_data:
  redis_data:


networks:
  enutritrack-network:
    driver: bridge
